//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public int activityId { get; set; }
        public string title { get; set; }
        public string time { get; set; }
        public string date { get; set; }
        public string location { get; set; }
        public string ootd { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
